; ESP32 (DOIT DEVKIT V1) 설정
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 업로드 속도 (빠르게)
upload_speed = 921600
monitor_speed = 115200

; ★ 여기가 자동 설치 목록입니다! ★
lib_deps =
    knolleary/PubSubClient @ ^2.8      ; MQTT 통신용
    madhephaestus/ESP32Servo @ ^1.1.0  ; 서보모터 (ESP32 전용 필수!)
    waspinator/AccelStepper @ ^1.64    ; 스텝모터 제어용
